# Generated by Django 5.0 on 2024-01-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.CharField(max_length=50, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='preview')),
                ('date_created', models.DateField(verbose_name='date_created')),
                ('feature', models.TextField(max_length=50, verbose_name='feature')),
                ('view_count', models.IntegerField(verbose_name='view_count')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
