# Generated by Django 5.0 on 2024-01-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_feature_alter_blog_slug_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is_published'),
        ),
    ]
