# Generated by Django 5.0 on 2024-01-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='feature',
        ),
    ]
