# Generated by Django 5.0.1 on 2024-01-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_create',
        ),
        migrations.AlterField(
            model_name='product',
            name='change_data',
            field=models.CharField(blank=True, null=True, verbose_name='change_data'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
    ]
