# Generated by Django 5.0.1 on 2024-01-18 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_date_create_alter_product_change_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_version', models.CharField(max_length=10, verbose_name='number_version')),
                ('name_version', models.CharField(max_length=30, verbose_name='name_version')),
                ('active_version', models.BooleanField(default=True, verbose_name='actual_version')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
            },
        ),
    ]
