# Generated by Django 4.2.7 on 2024-01-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_is_published', "Can cancel product's publication")], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
