# Generated by Django 4.2.7 on 2024-01-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published_status', "Can cancel product's publication")], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
